### PR TITLE
Fall state fix

### PR DESCRIPTION
**Pull request by jbussing**
Fix for https://github.com/mrbwaters/fire_drill/issues/4

### CODE REVIEW

**Comment by jbussing** [comment]
@mrbwaters or @eddivita  please review and approve 😀

**Comment by mrbwaters** [comment]
Looks like this has a small conflict with the changes I pushed in my PR.

Can you take a look and resolve?

I think it was just some cleanup I did to obj_player's step event.

**Comment by eddivita** [comment]
Propose to supersede this branch with Eddie Testing. Not sure if that is best way to handle these requests, but I duplicated this branch into my testing, and then made some major revisions that I'd like to bring into Main.

**Comment by mrbwaters** [comment]
Sounds good to me.

@jbussing, after you check Ed's code, will you close this PR and delete the branch?

Unfortunately, the fall state issue persists after these changes 🐛

**Comment by mrbwaters** [comment]
I'm not sure how this got merged. I don't think I consciously did it.
Maybe it got mixed in with Ed's PR that I merged?

**Pull request merged**
